In [1]:
#Stage 1:  model creation
import pandas as pd # is a python library used for data analysis & data manupulation ,it helps to work with tables,spreadsheets fles & large datasets 
from pandas import read_csv # Used to read data from csv file Stage : Data collection
#print(dir(pd))

In [7]:
dataset=pd.read_csv("Salary_Data.csv")# reading csv file

In [8]:
dataset # checking the value

    YearsExperience    Salary
0               1.1   39343.0
1               1.3   46205.0
2               1.5   37731.0
3               2.0   43525.0
4               2.2   39891.0
5               2.9   56642.0
6               3.0   60150.0
7               3.2   54445.0
8               3.2   64445.0
9               3.7   57189.0
10              3.9   63218.0
11              4.0   55794.0
12              4.0   56957.0
13              4.1   57081.0
14              4.5   61111.0
15              4.9   67938.0
16              5.1   66029.0
17              5.3   83088.0
18              5.9   81363.0
19              6.0   93940.0
20              6.8   91738.0
21              7.1   98273.0
22              7.9  101302.0
23              8.2  113812.0
24              8.7  109431.0
25              9.0  105582.0
26              9.5  116969.0
27              9.6  112635.0
28             10.3  122391.0
29             10.5  121872.0

In [9]:
independent=dataset[["YearsExperience"]] # from dataset fetching only yearsExperince column

In [10]:
independent

    YearsExperience
0               1.1
1               1.3
2               1.5
3               2.0
4               2.2
5               2.9
6               3.0
7               3.2
8               3.2
9               3.7
10              3.9
11              4.0
12              4.0
13              4.1
14              4.5
15              4.9
16              5.1
17              5.3
18              5.9
19              6.0
20              6.8
21              7.1
22              7.9
23              8.2
24              8.7
25              9.0
26              9.5
27              9.6
28             10.3
29             10.5

In [11]:
dependent=dataset[["Salary"]]# from dataset fetching only Salary column
dependent

      Salary
0    39343.0
1    46205.0
2    37731.0
3    43525.0
4    39891.0
5    56642.0
6    60150.0
7    54445.0
8    64445.0
9    57189.0
10   63218.0
11   55794.0
12   56957.0
13   57081.0
14   61111.0
15   67938.0
16   66029.0
17   83088.0
18   81363.0
19   93940.0
20   91738.0
21   98273.0
22  101302.0
23  113812.0
24  109431.0
25  105582.0
26  116969.0
27  112635.0
28  122391.0
29  121872.0

In [12]:
#stage: Split train and test
from sklearn.model_selection import train_test_split # sklearn is a pythin library and importing train_test_split
#below line : by assigning input and output values to the method and spliting the trainn and test data
X_train,X_test,Y_train,Y_test=train_test_split(independent,dependent,test_size=0.30,random_state=0)

In [14]:
from sklearn.linear_model import LinearRegression # importing LinearRegression class for model creation
regressor=LinearRegression()
#help(regressor.fit)
#stage:   train set
regressor.fit(X_train,Y_train)
#print(dir(regressor))
# stage : model creation
weight=regressor.coef_ #calculating weight
#help(regressor.coef_)
weight
#help(regressor.coef_)

array([[9360.26128619]])

In [16]:
bias=regressor.intercept_ #calculating bias
bias
#stage: Test set
y_pred=regressor.predict(X_test) # passing test inputs to get predicted  output

In [17]:
#stage: Evaluation metrics
#from sklearn library importing r2_score class to calculate the metrics if value is near to 1 then it is a good model
from sklearn.metrics import r2_score
r_score=r2_score(Y_test,y_pred) #passing test output and predicted output from model to calculate r2_score value

In [18]:
r_score # checking r_score value

0.9740993407213511

In [19]:
import pickle # pickle library used to save the best model
file_name="finalized_model_linear.sav"

In [20]:
# stage : Save the best model
pickle.dump(regressor,open(file_name,'wb'))# created model will be saved in file_name

In [21]:
# stage : Deployment
loaded_model=pickle.load(open(file_name,'rb')) # stage :loading the saved model
result=loaded_model.predict([[20]]) # stage: get inputs

C:\ProgramData\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

In [22]:
result

array([[213982.61706507]])